source .env

export SLACK_BOT_TOKEN=$SLACK_BOT_TOKEN
export SLACK_BOT_ID=$SLACK_BOT_ID
export ACCESS_TOKEN=$ACCESS_TOKEN
export REDDIT_CLIENT_ID=$REDDIT_CLIENT_ID
export REDDIT_CLIENT_SECRET=$REDDIT_CLIENT_SECRET
export REDDIT_USER=$REDDIT_USER
export REDDIT_PW=$REDDIT_PW


echo "initialized environment variables"
